[33기 이예은] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/33-backend-westagram-3 pull request #4
Opened 2022-05-13 08:17 UTC by yaeyunle

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- users/views.py & users/urls.py 수정
- westagram/views.py & westagram/urls.py 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 없습니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-05-13 09:11 UTC, lordmyshepherd requested changes

2022-05-13 09:11 UTC, lordmyshepherd commented on students/mia/users/views.py
> +                return JsonResponse({"message":"THE_USER_EMAIL_ALREADY_EXISTS"}, status=400)
`input_data('email')` 이 코드는 동작하는 코드인가요?

2022-05-13 09:11 UTC, lordmyshepherd commented on students/mia/users/views.py
> +                return JsonResponse({"message":"INVALID_EMAIL_OR_INVALID_PASSWORD"})
20번째 줄에 주석을 보면, 이메일이나 패스워드가 전달되지 않을 경우라고 했는데, 아래와 같이 client에서 email과 password는 제외하고 보내준 경우에 대한 에러 처리인가요?
```bash
http -v GET 127.0.0.1:8000/users mobile_number="010-6666-9999" name="예은님"
```
그렇다면, line 21~22 코드는 실행될 수가 없습니다. 그 이유는 input_data에 ['email'] 형태로 값에 접근할 때, input_data 안에 email이 없으면 KeyError를 발생시켜버리기 때문입니다.

2022-05-16 06:27 UTC, autoboy4commit commented on students/mia/users/views.py
> +                return JsonResponse({"message":"PASSWORD_REQUIRES_A_COMBINATION_OF_MIMIMUM_EIGHT_LETTERS,NUMBERS,AND_SPECIAL_SYMBOLS"}, status=400)
파이썬 PEP 8 프로그래밍 권고에는 비교문 관련해서 어떤 형식을 사용하라고 안내되어 있습니다.

- True/False를 비교할 때는 if문에 변수만 사용하도록 한다.
- 동등성(단순히 값만 비교하는 경우)을 검증할 때는 == 혹은 != 같은 연산자를 사용하도록 한다.
- 동일성(객체의 고유 메모리 주소로 비교하는 경우)을 검증할 때는 is나 is not을 사용한다.

```suggestion
            if not re.match(r"^[a-zA-Z0-9+-_.]+@/[a-zA-Z0-9-.]+\.[a-zA-Z0-9-]$", input_data['email']):
                return JsonResponse({"message":"INVALID_EMAIL_--_NEEDS_@_AND_."}, status=400)
            # 비밀번호는 8자리 이상, 문자 숫자, 특수문자의 복합 -- 그러지 않을 경우, 에러 반환
            if not re.match(r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$", input_data["password"]):
                return JsonResponse({"message":"PASSWORD_REQUIRES_A_COMBINATION_OF_MIMIMUM_EIGHT_LETTERS,NUMBERS,AND_SPECIAL_SYMBOLS"}, status=400)
```

2022-05-16 06:39 UTC, autoboy4commit commented
LGTM 👍

2022-05-16 06:39 UTC, merged